### ISSUE TITLE
Network Miner Crash

### ISSUE THREAD

**Issue by Emyrk** [pegnet/pegnet#209]
```
WARN[73800] Failed to get response from Kitco             error="Get https://www.kitco.com/market/: net/http: TLS handshake timeout"
ERRO[73800] failed to make opr                            error="failed to access Kitco Website : Get https://www.kitco.com/market/: net/http: TLS handshake timeout" evt=grader func=ForwardMonitorEvents
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x864ce9]

goroutine 1 [running]:
github.com/pegnet/pegnet/networkMiner.(*MiningServer).ForwardMonitorEvents(0xc0002001b0)
	/home/factom/go/github.com/pegnet/pegnet/networkMiner/server.go:174 +0x789
github.com/pegnet/pegnet/cmd.glob..func6(0xe3ecc0, 0xc0001a2380, 0x0, 0x2)
	/home/factom/go/github.com/pegnet/pegnet/cmd/cmd.go:292 +0x198
github.com/spf13/cobra.(*Command).execute(0xe3ecc0, 0xc0001a2320, 0x2, 0x2, 0xe3ecc0, 0xc0001a2320)
	/home/factom/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xe3f1c0, 0xc000260200, 0xc000260200, 0xc000260200)
	/home/factom/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/factom/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/pegnet/pegnet/cmd.Execute()
	/home/factom/go/github.com/pegnet/pegnet/cmd/root.go:85 +0x32
main.main()
	/home/factom/go/github.com/pegnet/pegnet/pegnet.go:8 +0x20
```

**Comment by Emyrk** [comment]
https://github.com/pegnet/pegnet/pull/210
